# Generated by Django 5.0.3 on 2024-03-21 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Цена')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1880), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Пробег')),
                ('power_engien', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='Мощность двигателя')),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Объем двигателя')),
                ('broken', models.BooleanField(blank=True, default=False, verbose_name='Битый')),
            ],
            options={
                'verbose_name': 'Объявления',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_body', models.CharField(max_length=50, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Тип кузова',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='DriveUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_drive_unit', models.CharField(max_length=50, verbose_name='Привод')),
            ],
            options={
                'verbose_name': 'Привод',
                'verbose_name_plural': 'Привод',
            },
        ),
        migrations.CreateModel(
            name='FavoriteAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранные объявления',
                'verbose_name_plural': 'Избранные объявления',
            },
        ),
        migrations.CreateModel(
            name='HandDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hand_drive', models.CharField(max_length=50, verbose_name='Руль')),
            ],
            options={
                'verbose_name': 'Руль',
                'verbose_name_plural': 'Руль',
            },
        ),
        migrations.CreateModel(
            name='ImageAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adverts/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Фото объявлений',
                'verbose_name_plural': 'Фото объявлений',
            },
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transmission', models.CharField(max_length=50, verbose_name='Трансмиссия')),
            ],
            options={
                'verbose_name': 'Трансмиссия',
                'verbose_name_plural': 'Трансмиссия',
            },
        ),
        migrations.CreateModel(
            name='TypeEngien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_engien', models.CharField(max_length=50, verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Тип двигателя',
                'verbose_name_plural': 'Тип двигателя',
            },
        ),
    ]
