# Generated by Django 5.0.3 on 2024-03-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_adverts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='advert',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.body', verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='advert',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.brand'),
        ),
        migrations.AddField(
            model_name='advert',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='advert',
            name='drive_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.driveunit', verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='favoriteadvert',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_advert', to='adverts.advert', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='favoriteadvert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='advert',
            name='users',
            field=models.ManyToManyField(related_name='advert', through='adverts.FavoriteAdvert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advert',
            name='hand_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.handdrive', verbose_name='Руль'),
        ),
        migrations.AddField(
            model_name='imageadvert',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adverts.advert'),
        ),
        migrations.AddField(
            model_name='modelauto',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.brand'),
        ),
        migrations.AddField(
            model_name='advert',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.modelauto'),
        ),
        migrations.AddField(
            model_name='advert',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.transmission', verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='advert',
            name='type_engien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.typeengien', verbose_name='Тип двигателя'),
        ),
    ]
